name: liquid_glass_container
description: "A beautiful Apple-style liquid glass container for Flutter, featuring realistic blur, refraction, and distortion effects. Lightweight, customizable, and perfect for modern UI design."
version: 1.0.0
homepage: "https://github.com/VishnuB01/radar_chart_plus/blob/main/README.md"
repository: "https://github.com/VishnuB01/liquid_glass_container"
topics:
  - liquid-glass
  - shader
  - glassmorphism
  - container
  - apple

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:


environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  shaders:
    - shaders/liquid_glass.frag