name: liquid_glass_container_plus
description: "A beautiful Apple-style liquid glass container for Flutter, featuring realistic blur, refraction and distortion effects. Lightweight, customizable and perfect for modern UI design."
version: 1.0.5
homepage: "https://github.com/VishnuB01/radar_chart_plus/blob/main/README.md"
repository: "https://github.com/VishnuB01/liquid_glass_container"
topics:
  - liquid-glass
  - shader
  - glassmorphism
  - container
  - apple

screenshots:
  - description: "This image shows a sample of the liquid glass container's refraction"
    path: screenshots/screen_shot.jpg
platforms:
  android:
  ios:
  linux:
  macos:

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  shaders:
    - shaders/liquid_glass.frag